from .language_model.omni_speech_llama import OmniSpeechLlamaForCausalLM, OmniSpeechConfig
from .language_model.omni_speech2s_llama import OmniSpeech2SLlamaForCausalLM
# from .language_model.omni_speech2s_parallel_llama import OmniSpeech2SParallelLlamaForCausalLM
from .language_model.omni_speech_qwen2 import OmniSpeechQwen2ForCausalLM, OmniSpeechConfig
from .language_model.omni_speech2s_qwen2 import OmniSpeech2SQwen2ForCausalLM
